import 'dart:async';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_html_to_pdf_plus/flutter_html_to_pdf_plus.dart';
import 'package:flutter_widget_from_html_core/flutter_widget_from_html_core.dart';
import 'package:hermosa_pos/utils/paper_width_utils.dart';
import 'package:path_provider/path_provider.dart';
import 'package:printing/printing.dart';
import 'package:pdf/pdf.dart';
import 'package:screenshot/screenshot.dart';

import '../models/receipt_data.dart';
import '../models.dart';
import 'invoice_print_widget.dart';
import '../locator.dart';
import '../services/printer_service.dart';

/// Cross-platform invoice preview and print screen.
///
/// Renders the invoice using InvoicePrintWidget for better display
/// or falls back to HTML rendering for compatibility.
///
/// Thermal / receipt-printer support is provided through the [printing]
/// package which talks to CUPS (Linux), Windows Spooler, and Android/iOS
/// native printing APIs.
class PdfPreviewScreen extends StatefulWidget {
  /// Remote PDF URL (legacy; maintained for backward compatibility).
  final String? pdfUrl;

  /// Path to a local .html or .pdf file generated by InvoiceHtmlPdfService.
  final String? localPdfPath;

  /// Raw HTML string to render directly (fallback path).
  final String? htmlContent;

  /// Invoice data for Widget rendering (preferred path for display).
  final OrderReceiptData? receiptData;

  /// Printer configuration for thermal printing.
  final DeviceConfig? printer;

  /// If true, prompt for printing immediately after opening.
  final bool promptPrinterSelectionOnOpen;

  /// If true, attempt to prefer the provided printer when auto-printing.
  final bool forcePreferredPrinter;

  /// Optional label for the print button.
  final String? printButtonLabel;

  /// Additional order data
  final String? orderType;
  final String? tableNumber;
  final String? carNumber;
  final String? dailyOrderNumber;
  final String? carBrand;
  final String? carModel;
  final String? carPlateNumber;
  final String? carYear;
  final String? clientName;
  final String? clientPhone;
  final String? clientTaxNumber;
  final String? commercialRegisterNumber;
  final String? returnPolicy;

  final String title;

  const PdfPreviewScreen({
    super.key,
    this.pdfUrl,
    this.localPdfPath,
    this.htmlContent,
    this.receiptData,
    this.printer,
    this.orderType,
    this.tableNumber,
    this.carNumber,
    this.dailyOrderNumber,
    this.carBrand,
    this.carModel,
    this.carPlateNumber,
    this.carYear,
    this.clientName,
    this.clientPhone,
    this.clientTaxNumber,
    this.commercialRegisterNumber,
    this.returnPolicy,
    this.promptPrinterSelectionOnOpen = true,
    this.forcePreferredPrinter = false,
    this.printButtonLabel,
    this.title = 'معاينة الفاتورة',
  });

  @override
  State<PdfPreviewScreen> createState() => _PdfPreviewScreenState();
}

class _PdfPreviewScreenState extends State<PdfPreviewScreen> {
  String _htmlContent = '';
  bool _isLoading = true;
  String? _error;
  bool _isPrinting = false;
  final ScreenshotController _screenshotController = ScreenshotController();
  bool _autoPrintTriggered = false;

  PdfPageFormat get _receiptPageFormat {
    final widthMm =
        normalizePaperWidthMm(widget.printer?.paperWidthMm ?? 58).toDouble();
    return PdfPageFormat(widthMm * PdfPageFormat.mm, double.infinity);
  }

  double get _previewMaxWidth => invoicePreviewMaxWidthForPaper(
        widget.printer?.paperWidthMm ?? 58,
      );

  @override
  void initState() {
    super.initState();
    // If we have receiptData, skip HTML loading
    if (widget.receiptData != null) {
      _isLoading = false;
      _triggerAutoPrintIfNeeded();
    } else {
      unawaited(_loadContent());
    }
  }

  // ────────────────────────────────────────────────────────────────────────────
  // Content loading
  // ────────────────────────────────────────────────────────────────────────────

  Future<void> _loadContent() async {
    try {
      if (widget.htmlContent != null && widget.htmlContent!.trim().isNotEmpty) {
        // Directly provided HTML – best path.
        _htmlContent = widget.htmlContent!;
      } else if (widget.localPdfPath != null &&
          widget.localPdfPath!.trim().isNotEmpty) {
        final path = widget.localPdfPath!.trim();
        if (path.toLowerCase().endsWith('.html')) {
          _htmlContent = await File(path).readAsString();
        } else {
          // PDF file – we can't render it inline, but we can still print it.
          _htmlContent = '';
          _error = null;
        }
      } else if (widget.pdfUrl != null && widget.pdfUrl!.trim().isNotEmpty) {
        // Remote PDF URL – fallback.
        _htmlContent = '';
        _error = null;
      }
    } catch (e) {
      _error = 'تعذر تحميل بيانات الفاتورة: $e';
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
        _triggerAutoPrintIfNeeded();
      }
    }
  }

  void _triggerAutoPrintIfNeeded() {
    if (!widget.promptPrinterSelectionOnOpen) return;
    if (_autoPrintTriggered) return;
    if (_isLoading) return;
    _autoPrintTriggered = true;
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (!mounted) return;
      if (widget.receiptData != null) {
        // For widget-based receipts, try direct thermal print.
        unawaited(_printThermalFromWidget());
      } else {
        // For HTML/PDF previews, open printer selection.
        unawaited(_directPrintToThermal());
      }
    });
  }

  // ────────────────────────────────────────────────────────────────────────────
  // HTML → PDF conversion
  // ────────────────────────────────────────────────────────────────────────────

  /// Converts HTML to PDF bytes.
  ///
  /// Uses flutter_html_to_pdf on Android/iOS where it is available.
  /// Falls back to writing an HTML file and printing directly on desktop.
  Future<Uint8List?> _htmlToPdfBytes(String html) async {
    try {
      final outputDir = await getTemporaryDirectory();
      final fileName = 'print_${DateTime.now().millisecondsSinceEpoch}';
      final file = await FlutterHtmlToPdf.convertFromHtmlContent(
        content: html,
        configuration: PrintPdfConfiguration(
          targetDirectory: outputDir.path,
          targetName: fileName,
        ),
      );
      return await file.readAsBytes();
    } on MissingPluginException {
      // Desktop platforms don't support flutter_html_to_pdf.
      return null;
    } catch (e) {
      final lower = e.toString().toLowerCase();
      if (lower.contains('missingpluginexception') ||
          lower.contains('no implementation found')) {
        return null;
      }
      debugPrint('⚠️ HTML→PDF conversion error: $e');
      return null;
    }
  }

  // ────────────────────────────────────────────────────────────────────────────
  // Printing
  // ────────────────────────────────────────────────────────────────────────────

  /// Print using the [printing] package.
  ///
  /// On **Android** this opens the system print dialog.
  /// On **Linux** it goes through CUPS.
  /// On **Windows** it uses the Windows Spooler / native print dialog.
  Future<void> _printInvoice() async {
    if (_isPrinting) return;
    setState(() => _isPrinting = true);

    try {
      if (_htmlContent.isNotEmpty) {
        // Try to generate a PDF from HTML first.
        final pdfBytes = await _htmlToPdfBytes(_htmlContent);

        if (pdfBytes != null && pdfBytes.isNotEmpty) {
          // We have a proper PDF – use it.
          await Printing.layoutPdf(
            onLayout: (_) => Future.value(pdfBytes),
            name: widget.title,
            format: _receiptPageFormat,
          );
        } else {
          // Desktop fallback: write the HTML to a temp file and use
          // Printing's built-in HTML printing support.
          final outputDir = await getTemporaryDirectory();
          final htmlFile = File(
              '${outputDir.path}/print_${DateTime.now().millisecondsSinceEpoch}.html');
          await htmlFile.writeAsString(_htmlContent, flush: true);

          // Try using Printing.layoutPdf with the deprecated but still
          // functional convertHtml API.
          try {
            // ignore: deprecated_member_use
            final convertedPdf = await Printing.convertHtml(
              html: _htmlContent,
              format: _receiptPageFormat,
            );
            await Printing.layoutPdf(
              onLayout: (_) => Future.value(convertedPdf),
              name: widget.title,
            );
          } catch (_) {
            // Last resort: open the HTML file in the system browser for
            // printing (mirrors old behavior but at least uses the right file).
            await _openHtmlInSystem(htmlFile.path);
          }
        }
      } else if (widget.localPdfPath != null) {
        // Already have a PDF file on disk.
        final file = File(widget.localPdfPath!.trim());
        if (await file.exists()) {
          final bytes = await file.readAsBytes();
          await Printing.layoutPdf(
            onLayout: (_) => Future.value(bytes),
            name: widget.title,
          );
        }
      }
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('تعذر بدء الطباعة: $e'),
          backgroundColor: Colors.red.shade700,
        ),
      );
    } finally {
      if (mounted) setState(() => _isPrinting = false);
    }
  }

  /// Opens a local HTML file using the system's default handler.
  Future<void> _openHtmlInSystem(String filePath) async {
    try {
      if (Platform.isLinux) {
        await Process.run('xdg-open', [filePath]);
      } else if (Platform.isWindows) {
        await Process.run('cmd', ['/c', 'start', '', filePath]);
      } else if (Platform.isMacOS) {
        await Process.run('open', [filePath]);
      }
    } catch (e) {
      debugPrint('⚠️ Could not open HTML file: $e');
    }
  }

  /// Direct-print to a specific printer (thermal / receipt).
  ///
  /// This tries to find available printers and sends the job directly,
  /// skipping the system print dialog. Useful for POS thermal printers.
  Future<void> _directPrintToThermal() async {
    if (_isPrinting) return;
    setState(() => _isPrinting = true);

    try {
      final printers = await Printing.listPrinters();
      if (printers.isEmpty) {
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Text('لم يتم العثور على طابعات متصلة'),
            backgroundColor: Colors.orange.shade700,
          ),
        );
        // Fallback to system print dialog.
        setState(() => _isPrinting = false);
        await _printInvoice();
        return;
      }

      // Show printer selection dialog.
      if (!mounted) return;
      final selectedPrinter = await showDialog<Printer>(
        context: context,
        builder: (ctx) => _PrinterSelectionDialog(printers: printers),
      );

      if (selectedPrinter == null) {
        // User cancelled.
        return;
      }

      Uint8List? pdfBytes;
      if (_htmlContent.isNotEmpty) {
        pdfBytes = await _htmlToPdfBytes(_htmlContent);

        // If HTML→PDF failed (desktop), try the deprecated but functional
        // convertHtml from the printing package.
        if (pdfBytes == null || pdfBytes.isEmpty) {
          try {
            // ignore: deprecated_member_use
            pdfBytes = await Printing.convertHtml(
              html: _htmlContent,
              format: _receiptPageFormat,
            );
          } catch (_) {
            // Will show error below.
          }
        }
      } else if (widget.localPdfPath != null) {
        pdfBytes = await File(widget.localPdfPath!.trim()).readAsBytes();
      }

      if (pdfBytes == null || pdfBytes.isEmpty) {
        if (!mounted) return;
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: const Text('تعذر تحويل الفاتورة إلى PDF للطباعة'),
            backgroundColor: Colors.red.shade700,
          ),
        );
        return;
      }

      final result = await Printing.directPrintPdf(
        printer: selectedPrinter,
        onLayout: (_) => Future.value(pdfBytes!),
        name: widget.title,
        format: _receiptPageFormat,
      );

      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            result
                ? 'تم إرسال الفاتورة إلى الطابعة ✅'
                : 'لم يتمكن من إرسال الفاتورة للطابعة ❌',
          ),
          backgroundColor: result ? Colors.green.shade700 : Colors.red.shade700,
        ),
      );
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('خطأ في الطباعة المباشرة: $e'),
          backgroundColor: Colors.red.shade700,
        ),
      );
    } finally {
      if (mounted) setState(() => _isPrinting = false);
    }
  }

  // ────────────────────────────────────────────────────────────────────────────
  // Build UI
  // ────────────────────────────────────────────────────────────────────────────

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        centerTitle: true,
      ),
      body: _buildBody(),
      bottomNavigationBar: SafeArea(
        child: Padding(
          padding: const EdgeInsets.fromLTRB(16, 8, 16, 16),
          child: widget.receiptData != null
              ? _buildThermalPrintButton()
              : _buildStandardPrintButtons(),
        ),
      ),
    );
  }

  /// Build thermal print button for Widget preview mode
  Widget _buildThermalPrintButton() {
    final label = _resolvePrintLabel();
    return SizedBox(
      width: double.infinity,
      height: 56,
      child: ElevatedButton.icon(
        onPressed: _isPrinting ? null : _printThermalFromWidget,
        icon: _isPrinting
            ? const SizedBox(
                width: 20,
                height: 20,
                child: CircularProgressIndicator(
                  strokeWidth: 2,
                  color: Colors.white,
                ),
              )
            : const Icon(Icons.print),
        label: Text(
          _isPrinting ? 'جارٍ الطباعة...' : label,
          style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
        ),
        style: ElevatedButton.styleFrom(
          backgroundColor: const Color(0xFF10B981),
          foregroundColor: Colors.white,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
        ),
      ),
    );
  }

  /// Build standard print buttons for HTML/PDF mode
  Widget _buildStandardPrintButtons() {
    final label = _resolvePrintLabel();
    return SizedBox(
      width: double.infinity,
      height: 56,
      child: ElevatedButton.icon(
        onPressed: _isPrinting ? null : _printInvoice,
        icon: _isPrinting
            ? const SizedBox(
                width: 20,
                height: 20,
                child: CircularProgressIndicator(
                  strokeWidth: 2,
                  color: Colors.white,
                ),
              )
            : const Icon(Icons.print),
        label: Text(
          _isPrinting ? 'جارٍ الطباعة...' : label,
          style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold),
        ),
        style: ElevatedButton.styleFrom(
          backgroundColor: const Color(0xFFF58220),
          foregroundColor: Colors.white,
          shape: RoundedRectangleBorder(
            borderRadius: BorderRadius.circular(12),
          ),
        ),
      ),
    );
  }

  /// Direct print using ESC/POS commands
  Future<void> _printThermalFromWidget() async {
    if (widget.printer == null) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('الرجاء اختيار طابعة من الإعدادات أولاً'),
          backgroundColor: Colors.orange,
        ),
      );
      return;
    }

    if (widget.receiptData == null) return;

    setState(() => _isPrinting = true);
    try {
      final printerService = getIt<PrinterService>();
      await printerService.printReceipt(
        widget.printer!,
        widget.receiptData!,
        jobType: 'preview_direct_print',
      );

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('تم إرسال الفاتورة للطابعة بنجاح ✅'),
            backgroundColor: Colors.green,
            duration: Duration(seconds: 2),
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('خطأ في الطباعة: $e'),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) setState(() => _isPrinting = false);
    }
  }

  String _resolvePrintLabel() {
    final label = widget.printButtonLabel?.trim();
    if (label != null && label.isNotEmpty) return label;
    return 'طباعة الفاتورة';
  }

  Widget _buildBody() {
    if (_isLoading) {
      return const Center(child: CircularProgressIndicator());
    }

    if (_error != null) {
      return Center(
        child: Padding(
          padding: const EdgeInsets.all(24),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              const Icon(Icons.error_outline, color: Colors.red, size: 42),
              const SizedBox(height: 12),
              Text(_error!, textAlign: TextAlign.center),
              const SizedBox(height: 12),
              ElevatedButton.icon(
                onPressed: () {
                  setState(() {
                    _isLoading = true;
                    _error = null;
                  });
                  _loadContent();
                },
                icon: const Icon(Icons.refresh),
                label: const Text('إعادة المحاولة'),
              ),
            ],
          ),
        ),
      );
    }

    // Use InvoicePrintWidget if we have receiptData (preferred)
    if (widget.receiptData != null) {
      return _buildWidgetPreview();
    }

    if (_htmlContent.isNotEmpty) {
      return _buildHtmlPreview();
    }

    // No HTML available (e.g. PDF-only path).
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            const Icon(Icons.picture_as_pdf, size: 56, color: Colors.red),
            const SizedBox(height: 12),
            const Text(
              'تم توليد الفاتورة. اضغط طباعة لإرسالها للطابعة.',
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 12),
            SizedBox(
              height: 46,
              child: ElevatedButton.icon(
                onPressed: _printInvoice,
                icon: const Icon(Icons.print),
                label: const Text('طباعة الفاتورة'),
              ),
            ),
          ],
        ),
      ),
    );
  }

  /// Builds the invoice preview using InvoicePrintWidget for better display.
  Widget _buildWidgetPreview() {
    return Container(
      color: const Color(0xFFF0F0F0),
      child: Center(
        child: SingleChildScrollView(
          physics: const BouncingScrollPhysics(),
          padding: const EdgeInsets.all(16),
          child: Container(
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(4),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withValues(alpha: 0.1),
                  blurRadius: 8,
                  offset: const Offset(0, 2),
                ),
              ],
            ),
            child: ClipRRect(
              borderRadius: BorderRadius.circular(4),
              child: Screenshot(
                controller: _screenshotController,
                child: InvoicePrintWidget(
                  data: widget.receiptData!,
                  paperWidthMm: widget.printer?.paperWidthMm ?? 58,
                  orderType: widget.orderType,
                  tableNumber: widget.tableNumber,
                  carNumber: widget.carNumber,
                  dailyOrderNumber: widget.dailyOrderNumber,
                  carBrand: widget.carBrand,
                  carModel: widget.carModel,
                  carPlateNumber: widget.carPlateNumber,
                  carYear: widget.carYear,
                  clientName: widget.clientName,
                  clientPhone: widget.clientPhone,
                  clientTaxNumber: widget.clientTaxNumber,
                  commercialRegisterNumber: widget.commercialRegisterNumber,
                  returnPolicy: widget.returnPolicy,
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }

  /// Renders the invoice HTML as native Flutter widgets.
  Widget _buildHtmlPreview() {
    return Container(
      color: const Color(0xFFF0F0F0),
      child: Center(
        child: SingleChildScrollView(
          padding: const EdgeInsets.symmetric(vertical: 24, horizontal: 8),
          child: Container(
            constraints: BoxConstraints(maxWidth: _previewMaxWidth),
            decoration: BoxDecoration(
              color: Colors.white,
              borderRadius: BorderRadius.circular(4),
              boxShadow: [
                BoxShadow(
                  color: Colors.black.withValues(alpha: 0.15),
                  blurRadius: 10,
                  offset: const Offset(0, 2),
                ),
              ],
            ),
            padding: const EdgeInsets.all(8),
            child: Directionality(
              textDirection: TextDirection.rtl,
              child: HtmlWidget(
                _htmlContent,
                textStyle: const TextStyle(
                  fontSize: 11,
                  fontFamily: 'Arial',
                  height: 1.3,
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

// ──────────────────────────────────────────────────────────────────────────────
// Printer selection dialog
// ──────────────────────────────────────────────────────────────────────────────

class _PrinterSelectionDialog extends StatelessWidget {
  final List<Printer> printers;

  const _PrinterSelectionDialog({required this.printers});

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text(
        'اختر الطابعة',
        textAlign: TextAlign.center,
        style: TextStyle(fontWeight: FontWeight.bold),
      ),
      content: SizedBox(
        width: double.maxFinite,
        child: ListView.separated(
          shrinkWrap: true,
          itemCount: printers.length,
          separatorBuilder: (_, __) => const Divider(height: 1),
          itemBuilder: (context, index) {
            final printer = printers[index];
            return ListTile(
              leading: Icon(
                printer.isDefault
                    ? Icons.local_printshop
                    : Icons.print_outlined,
                color:
                    printer.isDefault ? const Color(0xFFF58220) : Colors.grey,
              ),
              title: Text(
                printer.name,
                style: TextStyle(
                  fontWeight:
                      printer.isDefault ? FontWeight.bold : FontWeight.normal,
                ),
              ),
              subtitle: printer.isDefault
                  ? const Text(
                      'الطابعة الافتراضية',
                      style: TextStyle(
                        color: Color(0xFFF58220),
                        fontSize: 12,
                      ),
                    )
                  : null,
              onTap: () => Navigator.of(context).pop(printer),
            );
          },
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('إلغاء'),
        ),
      ],
    );
  }
}
